############
# Required #
############

variable "availability_zones" {
  type        = list(string)
  description = "List of availability zone id letters to use to create subnets"
}

############
# Optional #
############

variable "common_tags" {
  type        = map(any)
  description = "The tags to apply to all resources."
  default     = {}
}

variable "additional_subnet_types" {
  type        = list(string)
  description = "List of types of subnets to create, for each subnet type, a subnet will be created in each availability zone defined in `availability_zones`. The public, private, and db subnets are created by default and are not modified by this variable."
  default     = ["elasticache"]
}

variable "root_cidr" {
  type        = string
  description = "CIDR block to use for the vpc"
  default     = "10.0.0.0/16"
}

variable "region" {
  type        = string
  description = "The region to deploy the infrastructure to"
}

variable "ssm-role-suffix" {
  type        = string
  default     = ""
  description = "Value to append to the SSM role name, useful for deploying base infrastructure in another region where IAM names still conflict."
}

variable "dns_zone" {
  type        = string
  description = "The DNS name to use for the Route53 record"
}

variable "resource_name" {
  type        = string
  description = "Name generated by random_pet from root module"
}

### VPC Variables ###

variable "existing_vpc_id" {
  type        = string
  description = "ID of existing VPC to use"
}

variable "existing_private_subnets" {
  type        = list(string)
  description = "List of existing private subnet IDs"
}

variable "existing_public_subnets" {
  type        = list(string)
  description = "List of existing public subnet IDs"
}

variable "existing_database_subnets" {
  type        = list(string)
  description = "List of existing database subnet IDs"
}

variable "base_infra_workspace_name" {
  type        = string
  description = "Name of the base infrastructure workspace"
}